freebsd_instance:
  image: freebsd-13-0-current-amd64-v20200220
task:
  name: cargo test (stable)
  env:
    HOME: /tmp # cargo needs it
  install_script: pkg install -y rust
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build --all
  test_script: cargo test --all --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index
  
