matrix:
  env: ALLOW_FAILURES=0
  include:
    - os: windows
      language: rust
      rust:
        - stable
      before_script:
        - rustup toolchain install stable-x86_64-pc-windows-msvc
        - rustup default stable-msvc

    - os: windows
      language: rust
      rust:
        - nightly
      before_script:
        - rustup toolchain install nightly-x86_64-pc-windows-msvc
        - rustup default nightly-msvc
    
    - os: windows
      language: rust
      rust:
        - stable
      env: ALLOW_FAILURES=1

    - os: windows
      language: rust
      rust:
        - nightly
      env: ALLOW_FAILURES=1
        
    - os: linux
      language: rust
      rust:
        - stable
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9

    - os: linux
      language: rust
      rust:
          - nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9

    - os: osx
      language: rust
      rust:
        - stable

    - os: osx
      language: rust
      rust:
        - nightly
        
  allow_failures:     
    - env: ALLOW_FAILURES=1



script:
  - cargo test --all
  - cargo test --all --features 1mib
  - cargo test --all --features debug
  - cargo test --all --features cache-friendly

