matrix:
  include:
    - os: linux
      language: rust
      rust:
        - stable
        - beta
        - nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9


script:
  - cargo test --all
  - cargo test --all --features 1mib
  - cargo test --all --features debug
  - cargo test --all --features cache-friendly

