matrix:
  include:
    - os: linux
      language: rust
      rust:
        - stable
        - beta
        - nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


script:
  - cargo test --all
  - cargo test --all --features 1mib
  - cargo test --all --features debug
  - cargo test --all --features cache-friendly

