name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all
    - name: Run tests 1mib
      run: cargo test --all --features 1mib
    - name: Run tests 1mib build_cc
      run: cargo test --all --features build_cc
    - name: Run tests debug
      run: cargo test --all --features debug
    - name: Run tests cache-friendly
      run: cargo test --all --features cache-friendly

  crossbuild-mac-arm:
    runs-on: macOS-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: aarch64-apple-darwin
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        MACOSX_DEPLOYMENT_TARGET: '10.9'
      run: |
        # set SDKROOT for C dependencies
        export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
        cargo +nightly build --verbose --target aarch64-apple-darwin